[project]
name = "cli-socket-chat"
version = "0.3.0"
description = "Simple and secure CLI Chat"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography~=44.0.0",
    "pyreadline~=2.0; sys_platform == 'win32'",
    "rich>=13.9.4",
]
